name: Build Forge Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'

      - name: Set up Gradle 4.10.3
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 4.10.3

      - name: Generate Gradle Wrapper (compatible version)
        run: gradle wrapper --gradle-version 4.10.3

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build Mod
        run: ./gradlew buildAll

      - name: Upload Mod Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ShadowMods-Build
          path: build/libs/*.jar
